spring:
    application:
        name: friendsnet
    datasource:
        hikari:
            connection-timeout: 60000
            maximun-pool-size: 5
        url: jdbc:h2:mem:~/db_friendsnet;DB_CLOSE_DELAY=1000;DB_CLOSE_ON_EXIT=FALSE
    jpa:
        hibernate:
            ddl-auto: create-drop
logging:
    level:
        org.springframework: INFO
server:
    port: 8080